// <auto-generated />
namespace KQT.DataMigration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updateQuyenNgdung : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateQuyenNgdung));
        
        string IMigrationMetadata.Id
        {
            get { return "202004281009101_updateQuyenNgdung"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
